### ISSUE TITLE
Error in extract_1d

### ISSUE THREAD

**Issue by dfm** [adrn/GaiaPairsFollowup#3]
When I run extract_1d with my data, I'm getting:

"ERROR: Failed! NameError: name 'fit_spec_flux' is not defined [__main__]"

in the log. Is this something that I should be worried about?

**Comment by adrn** [comment]
Yea, it stands for "I suck" -- I updated a bunch of internals but never got back to the extract script...I think I know what needs to be fixed, so let me take a looksie

**Comment by dfm** [comment]
I see that! I'm currently spelunking as well. It's great stuff that you're doing here though!

**Comment by adrn** [comment]
I made a lot of questionable decisions on the fly, and left some of my principles at the door - as far as i can tell that's called "reducing data"

**Comment by dfm** [comment]
It's amazing that any observational result has ever held up.

**Comment by adrn** [comment]
Has an observational result ever help up?

**Comment by adrn** [comment]
Last few commits I pushed *may* fix the issue for ya

**Comment by adrn** [comment]
Scratch that...after testing, still looks borked. Can spend a bit of time on it tomorrow but have to do some other things tonight. Clear skies!

**Comment by dfm** [comment]
Understood. Thanks!

**Comment by adrn** [comment]
@ruthangus and I fixed this and other issues last week, but I still owe her some time to help finish the reductions!
