### ISSUE TITLE
Figure missing

### ISSUE THREAD

**Issue by smoh** [adrn/GaiaPairsFollowup#6]
Fails to make:
```
! Package pdftex.def Error: File `separation-with-rave.pdf' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.948 ...dth=\linewidth]{separation-with-rave.pdf}
```

**Comment by adrn** [comment]
oops - try now

**Comment by smoh** [comment]
Works now, thanks!


On July 14, 2017 at 11:10:10 AM, Adrian Price-Whelan (
notifications@github.com) wrote:

oops - try now

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/adrn/GaiaPairsFollowup/issues/6#issuecomment-315384513>,
or mute the thread
